project:
  type: website
  output-dir: docs
website:
  title: "QR Assessment Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
format:
  html:
    theme: lumen
    css: styles.css